#!/usr/bin/env bash
set -eu
set -o pipefail

# Generates lua-ctags.unicode_printability_boundaries module given Unicode version.
# Should be executed from root lua-ctags directory.

url="https://www.unicode.org/Public/$1/ucd/UnicodeData.txt"
cache="scripts/UnicodeData-$1.txt"

if [ ! -e "$cache" ]; then
    wget -O "$cache" "$url"
fi

(
    echo "-- Autogenerated using data from $url";
    lua scripts/unicode_data_to_printability_module.lua < "$cache"
) > src/lua-ctags/unicode_printability_boundaries.lua
